### PR TITLE
Nipype syntax change

### PR DESCRIPTION
**Pull request by nrajamani3**

### CODE REVIEW

**Comment by josephmje** [comment]
The 'out' prefix was removed from the eddy quad interface in nipype v1.1.9. Should 'out' be re-added to nipype or removed from dmriprep?

**Comment by arokem** [comment]
Maybe someone could explain to me why this syntax was changed? If need be, we might support both here, but if there was a good reason to remove it from nipype, I don't think that it needs to be reintroduced just for this.

**Comment by josephmje** [comment]
https://github.com/nipy/nipype/pull/2825#discussion_r249313587

**Comment by arokem** [comment]
Thanks. That helps. I say let's not include the "out_" prefixes. Or in other words, we should revert this PR.

**Comment by arokem** [comment]
Implemented in #69

**Pull request merged**
